### ISSUE TITLE
Create jupyterlab_robotmode repository under MarketSquare

### ISSUE THREAD

**Issue by xylix** [MarketSquare/MarketSquare#19]
There's interest in Robot open source community to create and maintain this sort of project as discussed here https://github.com/robots-from-jupyter/robotkernel/issues/50 
Marketsquare could be a good place. First maintainer for this could be @martinRenou

**Comment by emanlove** [comment]
General questions about these moves - are you all moving parts of repositories ..or.. forking and moving those forks into MarketSquare ..or.. creating copies of existing repositories? ..or.. something else altogether?

I ask for several reasons. In building the concept of MarketSquare I am following the model of the Plone's Collective. As I recall they have a note or guideline in dealing with "ownership" and possible copyright/license/legal issues around non maintainers/ owners taking some open source project and bring it into the Collective without the asking of the current, even if absent, maintainers.

Let say I am not worried here. And I really really don't want to slow done any forward moment that is happening. Really I am just trying to learn myself how to help setup the MarketSquare process and philosophy so that we build long term success.

I might reach out to you all so I can learn a little more. Also if there is anything I can do to help please reach out.
